title: "O LEITOR"
subtitle: "Informativo Literário"
issn: "ISSN 296 5-3169"
email: "suporte@oleitor.info"
social:
  instagram: "https://www.instagram.com/_oleitoroficial"
  x: "https://x.com/OLeitorOficial_"
  youtube: ""
footer_note_1: "Periódico editado e gerenciado por Societas Libri"
footer_note_2: "Produzido e promovido por VALMI Projetos Gráficos e Comunicação"
